### ISSUE TITLE
JSON file cut off when sent with audio

### ISSUE THREAD

**Issue by lyndonlim27** [Synapxe-DNA/azure-conversational-assistant#32]
- Response gets cut off when consuming in frontend
- Encoded audio is able to fit into JSON and send to frontend
    - Tested in postman and able to receive the full json string
- There might be some issues with `getReader()` or `TextDecoder("utf-8")` as it causes an error when trying to parse into json

**Comment by Wilsven** [comment]
@John-David-Tan @lyndonlim27 Is this still an issue?

**Comment by lyndonlim27** [comment]
Issue resolved
